### ISSUE TITLE
use on Windows with VAC

### ISSUE THREAD

**Issue by veso266** [UoC-Radio/JMPXRDS#6]
Hi I was wondering if this can be compiled for windows and if its posible to use PORT Audio  http://www.portaudio.com/

instead of jack

Thanks for Anwsering and Best Regards

**Comment by gkiagia** [comment]
Hi,
JMPXRDS is not currently actively supporting windows. It has been developed for linux. However, we believe it should be possible to compile it on windows maybe with a few modifications (or not, if you run it on top of the new linux subsystem of windows 10). If you want to give it a try, send us some patches.

Regarding portaudio, this is not possible of course (the whole application has been developed as a native JACK filter). Is there a good use case for using portaudio instead of JACK? In my experience portaudio is a bit of a hassle, at least when used with JACK underneath, and our project would not benefit from it at all. Of course, again, if you want to patch it, feel free.
